	CREATE DATABASE SAMPLEPROJECT
ON
(
	NAME = 'SAMPLEPROJECT_mdf',
	FILENAME = 'D:\DuAnMauJava\SQL\SAMPLEPROJECT.mdf',
	SIZE = 5,
	MAXSIZE =50,
	FILEGROWTH = 5
)
LOG ON
(
	NAME = 'SAMPLEPROJECT_ldf',
	FILENAME = 'D:\DuAnMauJava\SQL\SAMPLEPROJECT.ldf',
	SIZE = 10MB,
	MAXSIZE =500MB,
	FILEGROWTH = 5MB
)
GO
USE SAMPLEPROJECT
GO
CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(20) PRIMARY KEY NOT NULL ,
	MATKHAU NVARCHAR(50) NOT NULL,
	HOTEN  NVARCHAR(50) NOT NULL,
	VAITRO INT NOT NULL
)
GO

CREATE TABLE CHUYENDE
(
	MACD VARCHAR(5) PRIMARY KEY NOT NULL,
	TENCD  NVARCHAR(50) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	HINH  NVARCHAR(50) NOT NULL,
	MOTA  NVARCHAR(255) NOT NULL 
)
GO
CREATE TABLE KHOAHOC 
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY,
	MACD VARCHAR(5) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYKG DATE NOT NULL,
	GHICHU NVARCHAR(255) NOT NULL,
	MANV NVARCHAR(20) NOT NULL,
	NGAYTAO DATE NOT NULL,
	FOREIGN KEY(MACD) REFERENCES CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
	-- khi có khóa học liên quan đến chuyên đề, mà xóa c	huyên đề thì không thểm khi update chuyên đề
	-- thi update lun khóa học
)
GO
CREATE TABLE NGUOIHOC 
(
	MANH VARCHAR(7) PRIMARY KEY NOT NULL,
	HOTEN  NVARCHAR(50) NOT NULL,
	GIOITINH BIT NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIENTHOAI VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	GHICHU NVARCHAR(255) NOT NULL,
	MANV NVARCHAR(20) NOT NULL,
	NGAYDK DATE NOT NULL,
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
)
GO
CREATE TABLE HOCVIEN
(
	MAHV INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT  NOT NULL,
	MANH VARCHAR(7) NOT NULL,
	DIEM FLOAT NOT NULL,
	FOREIGN KEY(MANH) REFERENCES NGUOIHOC(MANH) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY(MAKH) REFERENCES KHOAHOC(MAKH)
)
GO


